api:
  dashboard: true
experimental:
  kubernetesGateway:
    enabled: true
ingressRoute:
  healthcheck:
    enabled: true
providers:
  kubernetesCRD:
    allowExternalNameServices: true
    allowEmptyServices: true
  kubernetesIngress:
    allowExternalNameServices: true
    allowEmptyServices: true
logs:
  general:
    format: json
  access:
    enabled: true
    format: json
    fields:
      headers:
        defaultmode: keep
        names:
          Authorization: redact
metrics:
  prometheus:
    addRoutersLabels: true
  otlp:
    # enabled: true
    addRoutersLabels: true
# tracing:
#   addInternals: true
  # otlp:
  #   enabled: true
tlsStore:
  default:
    defaultCertificate:
      secretName: default-self-tls
globalArguments: []
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    memory: 200Mi
ports:
  web:
    forwardedHeaders:
      insecure: true
    # redirectTo:
    #   port: websecure
  websecure:
    forwardedHeaders:
      insecure: true
envFrom:
  - secretRef:
      name: gatekeeper-client
