deployments:
  - include: stage0
  - barrier: true
  - include: stage1
  - barrier: true
  - include: stage2
  - barrier: true
  - include: stage3

commonLabels:
  k-ship.target: {{ target.name }}
  k-ship.environment: {{ args.environment }}
