reloader:
  autoReloadAll: true
  reloadOnCreate: true
  syncAfterRestart: true
  reloadStrategy: annotations
  logFormat: json
  readOnlyRootFileSystem: true
  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  podMonitor:
    enabled: true
    metricRelabelings:
      - action: keep
        regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
        sourceLabels: [__name__]
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: ^(.*)$
        targetLabel: nodename
        replacement: $1
        action: replace
