---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: kcpg
    usernameSecret:
      name: kcpg
      key: keycloakUsername
    passwordSecret:
      name: kcpg
      key: keycloakPassword
    database: keycloak
  http:
    httpEnabled: true
  hostname:
    # hostname: localhost
    strict: false
    strictBackchannel: false
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  additionalOptions:
    - name: log-file-output
      value: "json"
    - name: log-console-output
      value: "json"
    - name: metrics-enabled
      value: "true"
    # - name: proxy
    #   value: "edge"
    - name: http-relative-path
      value: "/sso"
    # - name: hostname-debug
    #   value: "true"
