---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mycurlpod
  labels:
    app: mycurlpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycurlpod
  template:
    metadata:
      labels:
        app: mycurlpod
    spec:
      containers:
        - name: mycurlpod
          image: curlimages/curl