apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-rendered.yaml
  - https://github.com/prometheus-operator/kube-prometheus/raw/main/manifests/setup/namespace.yaml
  # - https://github.com/prometheus-operator/kube-prometheus/manifests/setup
