cluster:
  name: "{{ target.name }}-{{ args.environment }}"
externalServices:
  prometheus:
    tenantID: "1"
    host: http://kps-kube-prometheus-stack-prometheus:9090
    queryEndpoint: /prometheus
    writeEndpoint: /api/v1/push
    authMode: none
  loki:
    tenantID: "1"
    host: http://lgtm-loki-gateway
    authMode: none
  tempo:
    tenantID: "1"
    host: http://lgtm-tempo-query-frontend:3100
    authMode: none
metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
traces:
  enabled: true
# profiles:
#   enabled: true
receivers:
  jaeger:
    grpc:
      enabled: true
    thriftBinary:
      enabled: true
    thriftCompact:
      enabled: true
    thriftHttp:
      enabled: true
  zipkin:
    enabled: true
prometheus-operator-crds:
  enabled: false
alloy:
  logging:
    format: json
alloy-events:
  logging:
    format: json
alloy-logs:
  logging:
    format: json
alloy-profiles:
  logging:
    format: json
opencost:
  enabled: false
  opencost:
    exporter:
      defaultClusterId: "{{ target.name }}-{{ args.environment }}"
      extraEnv: {}
    customPricing:
      enabled: true
    carbonCost:
      enabled: true
    metrics:
      serviceMonitor:
        enabled: true
    prometheus:
      existingSecretName: ~
      username_key: ~
      password_key: ~
      external:
        url: http://lgtm-mimir-nginx/prometheus
