reloader:
  autoReloadAll: true
  reloadOnCreate: true
  syncAfterRestart: true
  logFormat: json
  deployment:
    resources:
      limits:
        cpu: 20m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 50Mi
  podMonitor:
    enabled: false
    # TODO : enable monitoring
