deployments:
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/controller
      ref:
        tag: v2.24.1
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/webui
      ref:
        tag: v2.24.1
  - path: cert-manager
  - path: gatewayAPI
  - path: keycloak
  - path: kubegres
  - path: monitoring
