apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 2
  template:
    metadata:
      labels:
        app: krakend
    spec:
      volumes:
        - name: krakend-configmap
          configMap:
            name: krakend-config
      containers:
        - name: krakend
          image: devopsfaith/krakend:2.6.3
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/bin/krakend"
          args:
            - "run"
            - "-d"
            - "-c"
            - "/etc/krakend/config/krakend.json"
            - "-p"
            - "8080"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: krakend-configmap
              mountPath: /etc/krakend/config
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: KRAKEND_PORT
              value: "8080"
