---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-traefik-dashboard
spec:
  forwardAuth:
    address: http://gogatekeeper.keycloak:3000/
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  routes:
    - match: PathPrefix(`/dashboard/`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: auth-traefik-dashboard
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api
spec:
  routes:
    - match: PathPrefix(`/api/`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: auth-traefik-dashboard
