---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - postgres
  - gogatekeeper
  - keycloak-initial-admin.yaml
  - realm-configmap.yaml
  - keycloak-discovery.yaml
  - keycloak-statefulset.yaml
  - keycloak-service.yaml
