---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oidc
resources:
  - postgres
  - keycloak-initial-admin.yaml
  - gatekeeper-client.yaml
  - realm-configmap.yaml
  - keycloak.yaml
