---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubegres
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: kubegres
  name: kubegres-leader-election-rolebinding
  namespace: kubegres-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubegres-leader-election-role
subjects:
- kind: ServiceAccount
  name: kubegres-controller-manager
  namespace: kubegres-system
