global:
  leaderElection:
    namespace: cert-manager
crds:
  enabled: true
enableCertificateOwnerRef: true
extraArgs:
  - --logging-format=json
resources:
  requests:
    cpu: 20m
    memory: 128Mi
  limits:
    # cpu: 100m
    memory: 128Mi
prometheus:
  servicemonitor:
    enabled: true
ingressShim:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      # cpu: 20m
      memory: 64Mi
webhook:
  extraArgs:
    - --logging-format=json
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      # cpu: 20m
      memory: 64Mi
cainjector:
  extraArgs:
    - --logging-format=json
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      # cpu: 100m
      memory: 64Mi
startupaipcheck:
  extraArgs:
    - --logging-format=json
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      # cpu: 20m
      memory: 64Mi
