global:
  leaderElection:
    namespace: cert-manager
crds:
  enabled: true
enableCertificateOwnerRef: true
extraArgs:
  - --logging-format=json
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 64Mi
prometheus:
  servicemonitor:
    enabled: true
ingressShim:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi
webhook:
  extraArgs:
    - --logging-format=json
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi
cainjector:
  extraArgs:
    - --logging-format=json
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
startupaipcheck:
  extraArgs:
    - --logging-format=json
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 128Mi
