---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline    
  logstash.conf: |
    input {
      beats {
        port => 5045
        ssl_enabled => false
      }
    }
    filter {

      json {
        skip_on_invalid_json => true
        source => message
      }

      grok {
        match => { "message" => [
            "%{TIMESTAMP_ISO8601:timestamp}\s+\[%{LOGLEVEL:level}\]\s*\[%{NUMBER:thread}\]\s+%{NOTSPACE:[source][file][name]}\s+%{NUMBER:[source][file][line_number]}:\s+%{GREEDYDATA:message}",
            "%{TIMESTAMP_ISO8601:timestamp} - \[%{NOTSPACE:thread}\] %{LOGLEVEL:level}\s+%{NOTSPACE:class}\s* - %{GREEDYDATA:message}",
            "\[%{TIMESTAMP_ISO8601:timestamp}\]\[%{LOGLEVEL:level}\s*\]\[%{NOTSPACE:class}\s*\]\s*\[%{NOTSPACE:thread}\]\s*%{GREEDYDATA:message}",
            "\[%{LOGLEVEL:level}\s*\]\s*%{TIMESTAMP_ISO8601:timestamp}\s*\[%{NOTSPACE:class}\s*\]\s*%{GREEDYDATA:message}",
            "%{TIMESTAMP_ISO8601:timestamp}\s+%{LOGLEVEL:level}\s+%{DATA:data}\s+%{GREEDYDATA:message}"
          ]
        }
      }

      mutate {
        rename => {
          "msg" => "message"
        }
      }

      kv {
        recursive => true
      }

      mutate {
        rename => {
          "msg" => "message"
          "log.level" => "level"
        }
      }

      mutate {
        lowercase => [ "level" ]
      }

    }
    output {
      opensearch {
        hosts => ["https://os-master:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
        user => "logstash"
        password => "R!TQ~Mw$wzz3uXD8"
        ssl => true
        ssl_certificate_verification => false
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0
          ports:
            - containerPort: 5045
              name: beats
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config
            - name: logstash-pipeline-volume
              mountPath: /usr/share/logstash/pipeline
          resources:
              limits:
                memory: "2Gi"
                cpu: "1000m"
              requests: 
                memory: "1Gi"
                cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: logstash-pipeline-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.conf
                path: logstash.conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5045
      targetPort: beats
      name: beats
