---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/opentelemetry-operator
      sourceRef:
        kind: GitRepository
        name: open-telemetry
        namespace: flux-system
  values:
    manager:
      serviceMonitor:
        enabled: true
        prometheusRule:
          enabled: true
