---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector-logs
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/opentelemetry-collector
      sourceRef:
        kind: GitRepository
        name: open-telemetry
        namespace: flux-system
  values:
    mode: daemonset
    presets:
      hostMetrics:
        enabled: true
      logsCollection:
        enabled: true
        includeCollectorLogs: true
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
        extractAllPodAnnotations: true
      kubeletMetrics:
        enabled: true
      kubernetesEvents:
        enabled: true
    config:
      exporters:
        otlp:
          endpoint: opentelemetry-collector-otel:4317
          tls:
            insecure: true
      service:
        pipelines:
          logs:
            exporters:
              - otlp
              - debug
            processors:
              - memory_limiter
              - k8sattributes
              - batch
          metrics:
            exporters:
              - otlp
              - debug
            processors:
              - memory_limiter
              - k8sattributes
              - batch
          traces:
            exporters:
              - otlp
              - debug
            processors:
              - memory_limiter
              - k8sattributes
              - batch
    ports:
      metrics:
        enabled: true
    clusterRole:
      create: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 200Mi
    serviceMonitor:
      enabled: true
      metricsEndpoints:
        - port: metrics
          interval: 10s
    prometheusRule:
      enabled: true
      defaultRules:
        enabled: true
    useGOMEMLIMIT: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector-otel
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/opentelemetry-collector
      sourceRef:
        kind: GitRepository
        name: open-telemetry
        namespace: flux-system
  values:
    mode: deployment
    presets:
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
        extractAllPodAnnotations: true
      clusterMetrics:
        enabled: true
    config:
      service:
        pipelines:
          logs:
            # exporters:
            #   - otlp
            #   - debug
            processors:
              - memory_limiter
              - k8sattributes
              - batch
          metrics:
            # exporters:
            #   - otlp
            #   - debug
            processors:
              - memory_limiter
              - k8sattributes
              - batch
          traces:
            # exporters:
            #   - otlp
            #   - debug
            processors:
              - memory_limiter
              - k8sattributes
              - batch
    ports:
      metrics:
        enabled: true
    clusterRole:
      create: true
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 1Gi
    serviceMonitor:
      enabled: true
      metricsEndpoints:
        - port: metrics
          interval: 10s
    prometheusRule:
      enabled: true
      defaultRules:
        enabled: true
    useGOMEMLIMIT: true
