apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crds
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.crds.yaml
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/helm-v2.13.1/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml
