apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.crds.yaml
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/helm-v2.13.1/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml
  - helm-rendered.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  # - https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
