image:
  pullPolicy: IfNotPresent
args:
  - -log-format=json
podSecurityContext:
  fsGroup: 2000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 64Mi
