---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: whoami
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth0-basic
spec:
  plugin:
    traefikoidc:
      contextPath: /whoami
      encryptionSecretFile: /oidc/encryption/encryption_secret.json
      idps:
        - name: default
          providerUrl: "https://dev-nzee4dwlqvyvcqb0.us.auth0.com/"
          postLogoutUrl: "https://127.0.0.1.nip.io/whoami"
          clientSecretFile: /oidc/auth0/auth0_client_secret.json
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  routes:
    - match: PathPrefix(`/whoami`)
      kind: Rule
      services:
        - name: whoami
          kind: Service
          port: web
      middlewares:
        - name: auth0-basic
