enableCertificateOwnerRef: true
extraArgs:
  - --logging-format json
resources:
  requests:
    cpu: 20m
    memory: 60Mi
  limits:
    cpu: 20m
    memory: 60Mi
prometheus:
  servicemonitor:
    enabled: true
    honorLabels: true
    namespace: monitoring
enableServiceLinks: true
cainjector:
  extraArgs:
    - --logging-format json
  resources:
    requests:
      cpu: 20m
      memory: 100Mi
    limits:
      cpu: 20m
      memory: 100Mi
webhook:
  extraArgs:
    - --logging-format json
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      cpu: 20m
      memory: 50Mi
startupaipcheck:
  extraArgs:
    - --logging-format json
