resources:
  requests:
    cpu: 20m
    memory: 60Mi
  limits:
    cpu: 20m
    memory: 60Mi
cainjector:
  resources:
    requests:
      cpu: 20m
      memory: 100Mi
    limits:
      cpu: 20m
      memory: 100Mi
webhook:
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      cpu: 20m
      memory: 50Mi
