logInfoStdout: true
logFormat: "json"
startupProbe:
  enabled: true
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 64Mi
metrics:
  serviceMonitor:
    enabled: true
  dashboards:
    enabled: true
