logInfoStdout: true
logFormat: "json"
startupProbe:
  enabled: true
resources:
  requests:
    cpu: 20m
    memory: 100Mi
  limits:
    # cpu: 50m
    memory: 100Mi
metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring
  dashboards:
    enabled: true
    namespace: monitoring
