apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: klugui
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/klugui`)
      kind: Rule
      services:
        - kind: Service
          name: kluctl-webui
          port: 8080
      middlewares:
        - name: strip-klugui-prefix
